Darkmode incongruencies
pioneers/pimulator-js pull request #138
Opened 2021-08-08 00:07 UTC by Thine-Sho

2021-08-08 02:51 UTC, kevonz31 submitted a review, later dismissed

2021-08-08 02:51 UTC, kevonz31 commented on templates/index.html
> -                <a class="nav-item nav-link" href="https://forms.gle/i4q48q7fxBxRxDSb6" target="_blank">Bug Reports/Feature Requests</a>
Make sure to only commit changes that are relevant to your code. It seems that your branch is behind. Make sure to pull before committing.

2021-08-08 02:51 UTC, kevonz31 commented on templates/index.html
> +
Same as prior comment.

2021-08-14 21:14 UTC, charleshong3 requested changes

2021-08-14 21:14 UTC, charleshong3 commented on templates/index.html
> +                                        </div>
It looks like this was also added in by accident while resolving a merge conflict. It should be deleted.

2021-08-18 02:37 UTC, nia-n approved these changes
lgtm

2021-08-18 02:40 UTC, charleshong3 approved these changes

2021-08-18 02:41 UTC, merged