Made robot.js use inches and scaled everything by 3 in base.js
pioneers/pimulator-js pull request #19
Opened 2020-10-31 21:43 UTC by charleshong3

3 pixels = 1 inch
Robot size = 60x80 pixels = 20x26.7 inches
Field size = 432x432 pixels = 144x144 inches

2020-10-31 21:54 UTC, baby-bell requested changes, later dismissed
just in general, use "const" for things that will not change, and "let" in place of "var".

2020-10-31 21:54 UTC, baby-bell commented on static/js/base.js
> +    var rotateStr = "rotate(" + dir + " " + (x + 30) + " " + (y + 40) + ")"
```suggestion
    let rotateStr = `rotate({dir} {x + 30} {y + 40})`
```

2020-10-31 21:54 UTC, baby-bell commented on static/js/base.js
> +    let x = state.X * scaleFactor;
```suggestion
    const scaledX = state.X * scaleFactor;
    const scaledY = state.Y * scaleFactor;
```

2020-11-02 23:55 UTC, kevonz31 approved these changes
Changes have been fixed.

2020-11-02 23:56 UTC, merged